import type { CSSProperties } from 'react'

export const C = {
  bg: '#f5f5f7',
  card: '#ffffff',
  text: '#1d1d1f',
  text2: '#86868b',
  line: '#e8e8ed',
  blue: '#0071e3',
  green: '#16a34a',
  greenBg: '#eaf7ef',
  orange: '#b25000',
  orangeBg: '#fff6e5',
  red: '#d70015',
  redBg: '#ffeceb',
  gray: '#e8e8ed',
}

export const T: Record<string, CSSProperties> = {
  page: {
    fontFamily: "-apple-system, 'SF Pro Text', 'Segoe UI', Roboto, system-ui, sans-serif",
    maxWidth: 640, margin: '0 auto', padding: '16px 16px 48px',
    backgroundColor: C.bg, minHeight: '100vh', color: C.text, boxSizing: 'border-box',
  },
  h1: { fontSize: 26, fontWeight: 700, letterSpacing: '-0.02em', margin: '8px 0 16px' },
  card: { backgroundColor: C.card, borderRadius: 16, padding: 20, marginBottom: 12, boxShadow: '0 1px 2px rgba(0,0,0,0.06)' },
  h2: { fontSize: 17, fontWeight: 600, margin: '0 0 12px' },
  h3: { fontSize: 15, fontWeight: 600, margin: '0 0 8px' },
  small: { fontSize: 13, color: C.text2, marginTop: 6 },
  tiny: { fontSize: 12, color: C.text2, marginTop: 2, marginBottom: 6 },
  row: { display: 'flex', justifyContent: 'space-between', fontSize: 15, marginBottom: 8, gap: 8 },
  total: { fontSize: 22, fontWeight: 700, letterSpacing: '-0.01em' },
  btn: { width: '100%', padding: '12px 16px', borderRadius: 980, border: 'none', background: C.blue, color: '#fff', fontSize: 15, fontWeight: 600, cursor: 'pointer', marginTop: 10 },
  btnWarn: { width: '100%', padding: '12px 16px', borderRadius: 980, border: 'none', background: C.orangeBg, color: C.orange, fontSize: 15, fontWeight: 600, cursor: 'pointer', marginTop: 10 },
  btnSmall: { padding: '8px 14px', borderRadius: 980, border: 'none', background: C.blue, color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  btnSecondary: { padding: '8px 14px', borderRadius: 980, border: 'none', background: C.gray, color: C.text, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  btnDanger: { padding: '8px 14px', borderRadius: 980, border: 'none', background: C.redBg, color: C.red, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  btnOff: { padding: '8px 14px', borderRadius: 980, border: 'none', background: C.gray, color: C.text2, fontSize: 13, fontWeight: 600, cursor: 'default' },
  input: { width: '100%', padding: '11px 12px', borderRadius: 10, border: '1px solid #d2d2d7', fontSize: 15, marginBottom: 8, boxSizing: 'border-box', background: '#fff' },
  select: { padding: '8px 10px', borderRadius: 10, border: '1px solid #d2d2d7', fontSize: 14, background: '#fff', boxSizing: 'border-box' },
  chipGreen: { display: 'inline-block', padding: '4px 12px', borderRadius: 980, background: C.greenBg, color: C.green, fontSize: 13, fontWeight: 600 },
  chipOrange: { display: 'inline-block', padding: '4px 12px', borderRadius: 980, background: C.orangeBg, color: C.orange, fontSize: 13, fontWeight: 600 },
  chipRed: { display: 'inline-block', padding: '4px 12px', borderRadius: 980, background: C.redBg, color: C.red, fontSize: 13, fontWeight: 600 },
  chipGray: { display: 'inline-block', padding: '4px 12px', borderRadius: 980, background: C.gray, color: C.text2, fontSize: 13, fontWeight: 600 },
  note: { padding: 12, borderRadius: 12, background: C.orangeBg, color: C.orange, fontSize: 13, fontWeight: 600, marginTop: 10 },
  noteGreen: { padding: 12, borderRadius: 12, background: C.greenBg, color: C.green, fontSize: 13, fontWeight: 600, marginTop: 10 },
  noteRed: { padding: 12, borderRadius: 12, background: C.redBg, color: C.red, fontSize: 13, fontWeight: 600, marginTop: 10 },
  divider: { height: 1, background: C.line, margin: '14px 0' },
  sub: { marginTop: 14, paddingTop: 14, borderTop: `1px solid ${C.line}` },
  msg: { padding: 12, borderRadius: 12, background: C.greenBg, color: C.green, marginBottom: 12, fontSize: 14, fontWeight: 600 },
  item: { background: '#fafafc', borderRadius: 12, padding: 12, marginBottom: 8 },
  link: { fontSize: 12, color: C.blue, fontWeight: 600, cursor: 'pointer', marginTop: 4 },
}
